### ISSUE TITLE
Markers don´t work in IE

### ISSUE THREAD

**Issue by visiondpc** [fridek/gmap#9] opened 2012-06-08 07:53 UTC
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

<script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.7.1.min.js" type="text/javascript"></script>

<script src="jquery.gmap.js" type="text/javascript"></script>

<script>
$(function(){
    $("#map").gMap({
        latitude: "fit",
        longitude: "fit",
        zoom: "fit",    
        markers: [{
                latitude: 51.5282128,
                longitude: 7.02943,
        }]
    });
});
</script>

Works fine in FireFox and Safari but IE 7,8,9 don´t show a map or any JS-Error. Without the markes it works in IE too.

**Comment by mmarton** [comment] 2012-06-08 14:35
The problem is with your trailing comma. It is invalid js code, but most browsers can handle it. Explorers don't.
change "longitude: 7.02943, }]" to "longitude: 7.02943 }]"

**Comment by visiondpc** [comment] 2012-06-08 14:41
THX, but without the comma it still dont´t work in IE.

**Comment by svenkuhn** [comment] 2012-06-11 12:58
Same issue. IE9 works fine until i add some markers. Funny behavior:
After pressing F12 (IE-Debuggmode) it works. Seams to me that markers are blocking autostarting plugin.

**Comment by svenkuhn** [comment] 2012-06-11 13:45
I tryed using the jquery.gmap.3.3.0.alpha.js that is used on the website. This one works fine in IE but now the popups don´t work.
Another problem in 3.3.2:
Clustering is not working.

**Comment by fridek** [comment] 2012-12-27 22:15
It was a while since I last updated gmap, but this issue was fixed with 3.3.3. I was careless enough to leave console.log somewhere in the code - it explains why IE had problem with it and why it went away when console was open.

**Closed as completed by fridek** 2012-12-27 22:15 UTC
